# Site wide configuration

title: Trond Bordewich
locale: en_US
description: Sharing stuff.
logo: site-logo.png
search: true
url: http://www.trondbordewich.com

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true
comments: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Trond Bordewich
  avatar: bio-photo.jpg
  email: trond.bordewich@gmail.com
  disqus-shortname: trondbordewich
  twitter: trbordew
  facebook: #username
  github: ZeldaIV
  stackexchange: http://stackoverflow.com/users/3198157/the-dude
  linkedin: trond-bordewich-75310a2
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics: UA-70752994-1
    verify: google-site-verification=jcjHrMs9t6C21d-8fbUkKfm7qUUeE4AJ0t1tjnAM7KQ
    ad-client:
    ad-slot:
  bing-verify:
